create table "User"(
    id int primary key generated by default as identity,
    firstname varchar,
    surname varchar,
    login varchar(20) not null,
    phone_number varchar check
        (phone_number similar to '^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$'),
    email varchar check (email similar to '^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$'),
    password char[] not null,
    gender varchar default 'NONE',
    created_at timestamp not null,
    non_locked bool default true
);

create table Role(
    id int primary key references "User"(id) on delete cascade,
    role varchar default 'USER'
);

create table Post(
    id int primary key generated by default as identity,
    user_id int references "User"(id) on delete cascade,
    heading varchar(50),
    text varchar(1000),
    path_to_image varchar,
    created_at timestamp not null
);